### ISSUE TITLE
Gracefully handling data on the backend by way of data structure concepts

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/photography-backend#4]
Having done a little work with data structures I am wanting to make sure I handle this issue on my server-side in a graceful and _scalable_ manner.

**Please leave comments here in the issue on best practice methods for handling this type of data in a scalable and performant manner. The idea here is not only to write the best algorithm for this case; but to garner a better understanding of how to implement data structure concepts in my own work. Being able to regurgitate code is not the end goal; it's to better understand _what_ the code is doing and _why_ it's the best case scenario. I welcome all input.**

Thank you in advance to all who participate!

# The Skinny

My friend will be able to upload pictures through the Cloudinary Widget for storage on their servers. Cloudinary will return to me a response body that is in the form of an array. This array can be one object (data on image) or multiples. The plan is to extract the `public_id` from each object and store in a collection in MongoDB for later use with front-end. The `public_id` is nothing more than a string (string = less data than hi-res photo freeing up my server). The below screenshot shows a typical format of one object in the array:

![screen shot 2017-01-03 at 2 06 11 pm](https://cloud.githubusercontent.com/assets/19720404/21626214/78d47cd8-d1d5-11e6-9ed9-63d0df751c65.png)

# The Problem
When this initially goes online I expect a large number of uploads at one time and less over the course of this applications life so being able to handle a high load immediately is important.

So basically what I am trying to accomplish is the following:
- Iterate over an array of _x_ length.
- Find the `public_id` key in the object.
- Push the value of `public_id` to the corresponding collection in MongoDB.

# My _Current_ Idea for a Solution

```javascript
// Store the response in a variable.
// Variable now constitutes an array of 1 to x objects.
const data = response.body;
// Callback function to be invoked by forEach loop.
// Will iterate over every element in the array.
const callback = object => {
  // Loop searching by key.
  for(key in object) {
    // Conditional: Only searching for: public_id.
    if(object.hasOwnProperty(key)){
      // Store public_id value in variable.
      const value = object[key];
      // Call insert method on 'photos' collection.
      photos.insert({
        public_id: value, // Add value from response to key of same namesake in document.
        createdAt: new Date(); // Log with createdAt timestamp.
      });
    } 
  }
}

data.forEach(callback);
```

**Comment by rockchalkwushock** [comment]
Using `Object.keys()` is a faster operations than `.hasOwnProperty()`:
http://stackoverflow.com/questions/30326452/why-is-object-keys-faster-than-hasownproperty

```javascript
const callback = object => {
  const keys = Object.keys(object); // returns array of properties.
  const i = keys.indexOf('public_id'); // returns index of public_id.
  photos.insert({
        public_id: object[keys[i]], // Add value from response to key of same namesake in document.
        createdAt: new Date() // Log with createdAt timestamp.
      });
};
```

**Comment by rockchalkwushock** [comment]
So at this point what I'm seeing via Big O Notation is:
```javascript
forEach() = O(n) // double the objects to iterate over and you double the time.
Object.keys() = O(n) // double the keys to iterate over and you double the time.
indexOf() = ??? // honestly not sure, I want to say O(1).
insert() = O(1) // constant process.
```

So if my analysis of this is correct then my best, average, & worst would all be `O(n)` correct?

**Comment by rockchalkwushock** [comment]
With assistance from @EQuimper the case below seems to be the best way to handle the data coming from Cloudinary and storing it on my database in both a scalable and performant manner.

```javascript
const data = req.body.result // the array of object(s) from the Cloudinary response.
const insertStuff = data.reduce((array, item) => {
  array.push({
    public_id: item.public_id,
    url: item.url,
    thumbnail_url: item.thumbnail_url
  }); 
  return array; // returns a newly created array of objects.
  }, []); // start the reduce method with an empty array.

// Inserts the newly created array of objects as multiple documents in the collection.
Photo.insertMany(insertStuff);
```

Now for an explanation as to what`reduce()`is doing _for my own benefit!!!_

`Reduce()`is a list transformation, which can express _**any**_ list transformation, unlike`map()`,`filter()`,`find()`, etc. It is a function performed on the array object that takes a callback funciton as well as a defined starting point for the first argument of the callback function (as seen below):

```javascript
data.reduce((array, item => { code here }, []);
```

In the case of the above algorithm I am wanting to return a transformed _list_ or array of objects from the initial array of objects called`data`. So on the very first loop the _array_ argument will take in the predefined empty array and then a new object will be _pushed_ to that array. 

```javascript
data.reduce((array, item) => {
  array.push({
    public_id: item.public_id,
    url: item.url,
    thumbnail_url: item.thumbnail_url
  }); 
 return array;
  }, []); 
```

So to break it down on the first iteration the following occurs:

```javascript
data.reduce([], data[0] => { // arguments are the empty array & the first index of the data array.
[].push({ // run the push method on the empty array, pushing the defined object to the array.
    public_id: item.public_id,
    url: item.url,
    thumbnail_url: item.thumbnail_url
  }); 
 return [{obj1}]; // return the now populated array.
}, [{obj1}]); // the starting point now changes to the newly returned populated array.
```

A second iteration would look like:

```javascript
data.reduce([{obj1}], data[1] => { 
[{obj1}].push({ 
    public_id: item.public_id,
    url: item.url,
    thumbnail_url: item.thumbnail_url
  }); 
 return [{obj1}, {obj2}]; 
}, [{obj1}, {obj2}]);
```

And so on and so forth...
For more information on`reduce()`visit [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

# Big O Notation coming soon....

**Comment by EQuimper** [comment]
Good job !!!

**Comment by rockchalkwushock** [comment]
# Big O Notation of Algorithm:

Initially I figured this to be O(n) because of the`reduce()`, but was unsure how`push()`,`insertMany()`, & the promise inside of`insertMany()`would affect the algorithms performance.

I took to StackOverflow (SO) to see what the community had to say about the algorithm and if there are any considerations to make when using functional programming &/or promises when trying to discern the performance of an algorithm. The post on SO can be found here:

[Big O Notation and functional programming in Javascript](http://stackoverflow.com/questions/41489719/big-o-notation-and-functional-programming-in-javascript/41491015#41491015)

I still need to research `insertMany()` from the Mongo library to see how it might effect the algorithm, but at this point in time it seems the algorithm is in fact a case of O(n).

```plaintext
Best case: O(n)
Average case: O(n)
Worst case: O(n)
```
